/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FootballRouteImport } from './routes/football'
import { Route as F1RouteImport } from './routes/f1'
import { Route as IndexRouteImport } from './routes/index'

const FootballRoute = FootballRouteImport.update({
  id: '/football',
  path: '/football',
  getParentRoute: () => rootRouteImport,
} as any)
const F1Route = F1RouteImport.update({
  id: '/f1',
  path: '/f1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/f1': typeof F1Route
  '/football': typeof FootballRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/f1': typeof F1Route
  '/football': typeof FootballRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/f1': typeof F1Route
  '/football': typeof FootballRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/f1' | '/football'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/f1' | '/football'
  id: '__root__' | '/' | '/f1' | '/football'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  F1Route: typeof F1Route
  FootballRoute: typeof FootballRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/football': {
      id: '/football'
      path: '/football'
      fullPath: '/football'
      preLoaderRoute: typeof FootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f1': {
      id: '/f1'
      path: '/f1'
      fullPath: '/f1'
      preLoaderRoute: typeof F1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  F1Route: F1Route,
  FootballRoute: FootballRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
